package com.example.wallpapernxt.model.photoId

data class photoId(
    val alt_description: String,
    val blur_hash: String,
    val color: String,
    val created_at: String,
    val current_user_collections: List<Any>,
    val description: Any,
    val downloads: Int,
    val exif: Exif,
    val height: Int,
    val id: String,
    val liked_by_user: Boolean,
    val likes: Int,
    val links: Links,
    val location: Location,
    val meta: Meta,
    val promoted_at: Any,
    val public_domain: Boolean,
    val related_collections: RelatedCollections,
    val sponsorship: Sponsorship,
    val tags: List<TagX>,
    val tags_preview: List<TagsPreview>,
    val topic_submissions: TopicSubmissionsXXXX,
    val topics: List<Any>,
    val updated_at: String,
    val urls: UrlsXXXXX,
    val user: UserXXXXX,
    val views: Int,
    val width: Int
)